### ISSUE TITLE
Reviewer assignment guarantee #250

### ISSUE THREAD

**Issue by petermattson** [mlperf/policies#25]
Moving Training Policies issue #250 here:

Example language for rules:

Every submission gets a review by another submitter. If you submit, you may have to do a review as assigned by the review committee. The review committee will strive to match the amount of review work to the amount of work put into the submission. Any submitter is free to review any other submitter, in addition to any assigned reviews.

Example Algorithm: the review committee will:

Stack rank by number of submissions
Assign reviewers in pairs walking down the stack rank
If an odd number of reviewers, the bottom 3 in the stack rank will review each other.

**Comment by bitfort** [comment]
This was solved in https://github.com/mlperf/training_policies/issues/370

**Comment by bitfort** [comment]
Closing as duplicate.
