### ISSUE TITLE
Update section 5.6.2

### ISSUE THREAD

**Issue by georgelyuan** [mlperf/policies#44]
"Inference benchmark directory names must be one of { mobilenet, ssd-small, resnet, ssd-large, gnmt }."
This needs to be updated for v0.7. Note that we are using '-99.9' and '-99' suffixes for the benchmarks where those apply.

**Comment by guschmue** [comment]
+ mobilenet is gone and there is now dlrm, 3d-unet, rnnt

**Comment by georgelyuan** [comment]
Are you submitting a PR to make that fix? Some of the benchmark names need to include the '-99' or '-99.9' suffixes.
