### ISSUE TITLE
Where do open submission results go

### ISSUE THREAD

**Issue by DilipSequeira** [mlperf/policies#5]
@guschmue @christ1ne @tjablin
Supposing an open submission with a given SUT/benchmark/scenario/ combination (it's a SW submission, so the SUTs are the same), what directory is appropriate for results?

I suggest another level in results, so it's results/closed/system_desc_id/... and then one for open. This leaves closed results uncluttered, which seems to me useful.

**Comment by guschmue** [comment]
I don't think there is a good way today. Having closed or open at the top level gets my vote.

**Comment by christ1ne** [comment]
agree with @guschmue as the closed and open are arranged in different tables in the displayed table on the website anyways.

I think last time we had a repo for closed and a repo for open. I recommend the same for this round @petermattson

**Comment by petermattson** [comment]
Added separate directories for open and closed.
